-- Durable provenance for built-in memory mutations, including removals.
CREATE TABLE memory_write_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    target VARCHAR(16) NOT NULL,
    action VARCHAR(16) NOT NULL,
    fact TEXT,
    old_fact TEXT,
    write_origin VARCHAR(64),
    execution_context VARCHAR(64),
    source_session_id TEXT,
    parent_session_id TEXT,
    platform VARCHAR(64),
    tool_name VARCHAR(128),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_memory_write_audit_user_created
    ON memory_write_audit(user_id, created_at DESC);
CREATE INDEX idx_memory_write_audit_source_session
    ON memory_write_audit(source_session_id);

